<?php
/**
 * Minimal multilingual SEO core for WEM Multilingual.
 *
 * Step 8 of v0.1.0 Experimental Core.
 *
 * Provides:
 * - self canonical
 * - hreflang en / es / x-default
 * - html lang for Spanish context
 *
 * Only explicitly published Spanish object versions participate in SEO output.
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

final class WEM_ML_SEO {

    public static function init() {
        add_filter( 'get_canonical_url', array( __CLASS__, 'filter_canonical_url' ), 20, 2 );
        add_action( 'wp_head', array( __CLASS__, 'output_hreflang' ), 3 );
        add_filter( 'language_attributes', array( __CLASS__, 'filter_language_attributes' ), 20, 2 );
    }

    /**
     * Build SEO data for one Page/Post object independently of current context.
     *
     * @param int $object_id Page/Post ID.
     * @return array<string,mixed>
     */
    public static function get_object_seo_data( $object_id ) {
        $object_id = absint( $object_id );
        $post      = get_post( $object_id );

        $empty = array(
            'object_id'       => $object_id,
            'object_type'     => '',
            'source_url'      => '',
            'spanish_url'     => '',
            'spanish_state'   => 'draft',
            'spanish_public'  => false,
            'canonical_en'    => '',
            'canonical_es'    => '',
            'hreflang_en'     => '',
            'hreflang_es'     => '',
            'x_default'       => '',
        );

        if ( ! $post || ! in_array( $post->post_type, array( 'page', 'post' ), true ) ) {
            return $empty;
        }

        $source_url = WEM_ML_Router::get_source_permalink( $object_id );
        $state      = WEM_ML_Object_State::get_status( $post->post_type, $object_id, 'es' );
        $slug       = WEM_ML_Slug_Repository::get_slug( $post->post_type, $object_id, 'es' );
        $spanish_url = '';

        if ( $slug ) {
            $spanish_url = WEM_ML_Router::get_localized_permalink(
                $post->post_type,
                $object_id,
                'es',
                $source_url
            );
        }

        $spanish_public = 'published' === $state
            && ! empty( $slug )
            && '' !== $spanish_url
            && $spanish_url !== $source_url;

        return array(
            'object_id'       => $object_id,
            'object_type'     => $post->post_type,
            'source_url'      => $source_url,
            'spanish_url'     => $spanish_url,
            'spanish_state'   => $state,
            'spanish_public'  => $spanish_public,
            'canonical_en'    => $source_url,
            'canonical_es'    => $spanish_public ? $spanish_url : '',
            'hreflang_en'     => $spanish_public ? $source_url : '',
            'hreflang_es'     => $spanish_public ? $spanish_url : '',
            'x_default'       => $spanish_public ? $source_url : '',
        );
    }

    /**
     * Make WordPress core canonical self-reference the current language URL.
     *
     * @param string  $canonical_url Canonical URL generated by WordPress.
     * @param WP_Post $post          Current post object.
     * @return string
     */
    public static function filter_canonical_url( $canonical_url, $post ) {
        if ( ! $post instanceof WP_Post || ! in_array( $post->post_type, array( 'page', 'post' ), true ) ) {
            return $canonical_url;
        }

        $data = self::get_object_seo_data( (int) $post->ID );

        if ( 'es' === WEM_ML_Language_Context::get_current_language() && $data['spanish_public'] ) {
            return (string) $data['canonical_es'];
        }

        return $data['canonical_en'] ? (string) $data['canonical_en'] : $canonical_url;
    }

    /**
     * Output hreflang only when the Spanish object version is explicitly public.
     */
    public static function output_hreflang() {
        if ( ! is_singular( array( 'page', 'post' ) ) ) {
            return;
        }

        $object_id = get_queried_object_id();

        if ( $object_id <= 0 ) {
            return;
        }

        $data = self::get_object_seo_data( $object_id );

        if ( ! $data['spanish_public'] ) {
            return;
        }

        printf(
            "\n<link rel=\"alternate\" hreflang=\"en\" href=\"%s\" />\n",
            esc_url( $data['hreflang_en'] )
        );
        printf(
            "<link rel=\"alternate\" hreflang=\"es\" href=\"%s\" />\n",
            esc_url( $data['hreflang_es'] )
        );
        printf(
            "<link rel=\"alternate\" hreflang=\"x-default\" href=\"%s\" />\n",
            esc_url( $data['x_default'] )
        );
    }

    /**
     * Switch the document language declaration only for Spanish context.
     * Source-language requests keep WordPress's existing language attributes.
     *
     * @param string $output  Existing language attributes.
     * @param string $doctype Document type.
     * @return string
     */
    public static function filter_language_attributes( $output, $doctype = 'html' ) {
        if ( 'es' !== WEM_ML_Language_Context::get_current_language() ) {
            return $output;
        }

        if ( preg_match( '/\blang=("|\')[^"\']*("|\')/i', $output ) ) {
            $output = preg_replace( '/\blang=("|\')[^"\']*("|\')/i', 'lang="es"', $output, 1 );
        } else {
            $output = 'lang="es" ' . ltrim( $output );
        }

        if ( false !== stripos( $output, 'xml:lang=' ) ) {
            $output = preg_replace( '/xml:lang=("|\')[^"\']*("|\')/i', 'xml:lang="es"', $output, 1 );
        }

        return trim( $output );
    }
}
